### ISSUE TITLE
Pimoroni stock incorrect?

### ISSUE THREAD

**Issue by lurch** [alexellis/pi_zero_stock#1]
According to http://stockalert.alexellis.io/ Pimoroni only has one PiZero in stock, which clearly isn't correct.

I did a bit of digging, and I _think_ these are the URLs you ought to be getting the data from instead?
https://shop.pimoroni.com/products/pi-zero-complete-starter-kit.json
https://shop.pimoroni.com/products/pi-zero-project-kits.json

I don't know if those URLs themselves can somehow be 'deduced' from the URL you're currently monitoring?

**Comment by lurch** [comment]
P.S. I didn't dig too deeply, but does it make sense for https://github.com/alexellis/pi_zero_stock/blob/master/stock_fetch/fetch/pihut.js to say `module.exports = class Pimoroni {` ?

**Comment by alexellis** [comment]
@lurch re: pihut.js that has no effect on the code fortunately, the exports ignores the Class name. Thanks for pointing it out.

The main page that is being processed is: https://shop.pimoroni.com/collections/pi-zero/products/raspberry-pi-zero - I guess the other pages arrived after the re-launch. With them included in the totals we have a more reasonable number.

https://github.com/alexellis/pi_zero_stock/commit/c24430d2467afd035ac53027abbac3edcd49d8d0

https://github.com/alexellis/pi_zero_stock/commit/adfc0a9b26440e2d2f5c0a78a1b054590c30a57e

Please do get in touch again if you notice anything wrong. 👍

**Comment by lurch** [comment]
Great :-)

Might also be useful to have a link to http://stockalert.alexellis.io/ somewhere on https://github.com/alexellis/pi_zero_stock ?

**Comment by alexellis** [comment]
@lurch Good idea, I've just updated it. Is there anyone you can share this with over at Pi Towers? Thanks

**Comment by lurch** [comment]
I don't work at Pi Towers... Might be worth getting in touch with @bennuttall though?

**Comment by alexellis** [comment]
Looking at your repo list I thought you may have had a contact on twitter ;-) I'll ping Ben.

**Comment by lurch** [comment]
I'm not on twitter... ;-)
