### ISSUE TITLE
Pimoroni stock-level is wrong

### ISSUE THREAD

**Issue by lurch** [alexellis/pi_zero_stock#12]
At the time-of-writing, https://shop.pimoroni.com/collections/pi-zero/products/raspberry-pi-zero shows:
Pi Zero Complete Starter Kit  26 in stock
Pi Zero + Project Kit  25 in stock
Pi Zero + Adaptors + Pibow Zero Case  19 in stock

and https://shop.pimoroni.com/collections/new-products/products/pi-zero-cctv-kit-little-bro shows:
Pi Zero CCTV Kit (Little Bro)  22 in stock

But http://stockalert.alexellis.io/ says:
pimoroni in stock  70 units

Something doesn't quite add up right... ;-)

**Comment by alexellis** [comment]
Have you had a look at the JSON files?

**Comment by lurch** [comment]
Hmmm, https://shop.pimoroni.com/products/raspberry-pi-zero.js says the "Pi Zero only" product has `"inventory_quantity":-22` !
I guess you might want to update your scripts to ignore negative quantities ;-)

**Comment by alexellis** [comment]
Current check:

```
if(v.inventory_quantity) {
                 let val = Number(v.inventory_quantity);
                 if(val > 0 && v.price > 0) {
                    total += val;
                 }
               }
```

Hmm

**Comment by lurch** [comment]
Well, it's a moot point now, because Pimoroni is fully-sold-out again :-/
But there was definitely _something_ going wrong with your "total" figure.

**Comment by lurch** [comment]
Aha! Now that PiZeros are back in stock again, I've finally got to the bottom of what's going wrong! :-D
Because https://shop.pimoroni.com/products/pi-zero-cctv-kit-little-bro.json is being read as a JSON file, rather than a JS file, there's an extra 'product' layer around the whole thing.

I dug into the problem using the [jq](https://stedolan.github.io/jq/) CLI tool...

The following massive one-liner (note the extra `.product` in the final jq invocation)

``` bash
JQFILTER='.variants | map(if .inventory_quantity > 0 then .inventory_quantity else empty end) | add'; for js in raspberry-pi-zero.js pi-zero-complete-starter-kit.js pi-zero-project-kits.js; do echo $js; wget -q -O - "https://shop.pimoroni.com/products/$js" | jq "$JQFILTER"; done; for json in pi-zero-cctv-kit-little-bro.json; do echo $json; wget -q -O - "https://shop.pimoroni.com/products/$json" | jq ".product$JQFILTER"; done
```

currently reports:

```
raspberry-pi-zero.js
1131
pi-zero-complete-starter-kit.js
148
pi-zero-project-kits.js
240
pi-zero-cctv-kit-little-bro.json
24
```

And http://stockalert.alexellis.io/ currently says pimoroni has 1519 units in stock (equal to 1131 + 148 + 240), confirming my original suspicion that your stockalert figure isn't including the CCTV kits.

So you either need to add separate parsers for JS and JSON feeds, or I guess you could switch them all to using only JS or only JSON.

Although confusingly, the JS and JSON files for `raspberry-pi-zero` are currently reporting different numbers...

``` bash
for feed in raspberry-pi-zero pi-zero-complete-starter-kit pi-zero-project-kits pi-zero-cctv-kit-little-bro; do file=$feed.json; echo $file; wget -q -O - "https://shop.pimoroni.com/products/$file" | jq ".product.variants | map(if .inventory_quantity > 0 then {product: .title, quantity: .inventory_quantity} else empty end)"; done
raspberry-pi-zero.json
[
  {
    "quantity": 366,
    "product": "Pi Zero + Adaptors + Pibow Zero Case"
  },
  {
    "quantity": 254,
    "product": "Pi Zero + Adaptors"
  },
  {
    "quantity": 534,
    "product": "Pi Zero only"
  }
]
pi-zero-complete-starter-kit.json
[
  {
    "quantity": 148,
    "product": "Default Title"
  }
]
pi-zero-project-kits.json
[
  {
    "quantity": 71,
    "product": "Scroll pHAT - Message Kit"
  },
  {
    "quantity": 83,
    "product": "Explorer pHAT - Electronics Kit"
  },
  {
    "quantity": 86,
    "product": "pHAT DAC - Wireless Audio Kit"
  }
]
pi-zero-cctv-kit-little-bro.json
[
  {
    "quantity": 24,
    "product": "Kit"
  }
]
```

vs.

``` bash
for feed in raspberry-pi-zero pi-zero-complete-starter-kit pi-zero-project-kits pi-zero-cctv-kit-little-bro; do file=$feed.js; echo $file; wget -q -O - "https://shop.pimoroni.com/products/$file" | jq ".variants | map(if .inventory_quantity > 0 then {product: .title, quantity: .inventory_quantity} else empty end)"; done
raspberry-pi-zero.js
[
  {
    "quantity": 366,
    "product": "Pi Zero + Adaptors + Pibow Zero Case"
  },
  {
    "quantity": 254,
    "product": "Pi Zero + Adaptors"
  },
  {
    "quantity": 511,
    "product": "Pi Zero only"
  }
]
pi-zero-complete-starter-kit.js
[
  {
    "quantity": 148,
    "product": "Default Title"
  }
]
pi-zero-project-kits.js
[
  {
    "quantity": 71,
    "product": "Scroll pHAT - Message Kit"
  },
  {
    "quantity": 83,
    "product": "Explorer pHAT - Electronics Kit"
  },
  {
    "quantity": 86,
    "product": "pHAT DAC - Wireless Audio Kit"
  }
]
pi-zero-cctv-kit-little-bro.js
[
  {
    "quantity": 24,
    "product": "Kit"
  }
]
```

Those sneaky pirates... ;-)  Any idea which one is the "more correct" @Gadgetoid ?

**Comment by alexellis** [comment]
Thanks for looking into this @lurch. Not sure about the `jq` command line plus you would need to include the logic for testing the price field too. Possibly more useful to run the code locally - Docker is not strictly required to execute the code.

https://github.com/alexellis/pi_zero_stock/pull/13

**Comment by lurch** [comment]
> Not sure about the jq command line

It's just a really neat command-line tool for slicing & dicing JSON data without having to write custom parsing scripts - perfect for one-liners and prototyping :-)

> plus you would need to include the logic for testing the price field too

Easily achieved by changing the `if .inventory_quantity > 0 then` in my examples above to `if .inventory_quantity > 0 and .price > 0 then`

> Possibly more useful to run the code locally - Docker is not strictly required to execute the code.

Afraid I currently have no interest in installing nodejs or npm either! Aren't I awkward... ;)
